import type { ChartFilterRequest, ChartResponse } from "@mantra4change/shared-types";
import { apiPost } from "./http";

export type ChartType =
  | "program-trends"
  | "district-performance"
  | "risk-distribution"
  | "grant-utilization";

const API_BASE = import.meta.env.VITE_API_BASE_URL ?? "";

export function fetchChart(
  chartType: ChartType,
  body: ChartFilterRequest,
): Promise<ChartResponse> {
  return apiPost<ChartResponse>(`/api/charts/${chartType}`, body);
}

export async function downloadChartPng(
  chartType: ChartType,
  body: ChartFilterRequest,
  fileName: string,
): Promise<void> {
  const chart = await fetchChart(chartType, { ...body, exportPng: true });
  if (!chart.pngPath) {
    throw new Error("Chart PNG was not generated by the analytics service");
  }

  const response = await fetch(
    `${API_BASE}/api/charts/download?path=${encodeURIComponent(chart.pngPath)}`,
  );
  if (!response.ok) {
    throw new Error("Failed to download chart PNG");
  }

  const blob = await response.blob();
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = fileName;
  anchor.click();
  URL.revokeObjectURL(url);
}
